# GoReleaser configuration for container-use
version: 2

project_name: container-use

before:
  hooks:
    - go mod tidy

builds:
  - id: cu
    binary: cu
    main: ./cmd/cu
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: cu-archive
    ids:
      - cu
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  draft: true
  prerelease: auto
  mode: replace
  header: |
    ## container-use {{ .Tag }}
    
    Download the pre-compiled binaries from the assets below.
  footer: |
    **Full Changelog**: https://github.com/dagger/container-use/compare/{{ .PreviousTag }}...{{ .Tag }}