name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release with Dagger
        uses: dagger/dagger-for-github@v8.0.0
        with:
          version: "latest"
          verb: call
          args: release --version "${GITHUB_REF#refs/tags/}" --github-token env:GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}